openapi: 3.0.2
servers:
  - url: http://localhost:{port}/api
    description: Localhost server
    variables:
      port:
        default: "3000"
        description: Port for local development
  - url: https://{server}/api
    description: Production server
    variables:
      server:
        default: api.example.com
        description: Server endpoint
info:
  title: Dash API
  version: "1.0.0"
